sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run lint
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: vv8PgX6+GQFIWa2gv/AE0kekCw6WHfJ3fT2OmuBn1HNSJkjKriBVUL3VeoxTq9GHnG9/MHvDZYYuFXwq9gfpgoDr26NZZ+AYyZbiZ8hZmOvArQtyvEKBUixcHUJLOkLT8TFnt/MpEdSytwB51yQHJeTYCvIHEHKP6hRNmO1K+R5jY/4rPGmsP5Vw1qwAPmiNg0tRBD639bonb47FsqkkFjpQcUofJKu8dvVtiqpwWdZhIzcTnb6KYa8jHwCIlbokZ+ByZlLhtoPj6dtMD1Me0c9H93SDRl5RIKN2ZEe5JFqL2u4rEgzXOS2ZqaFdY41qCflh4F/vuqC5CWQJyi5+6pj5znSgMTazuvqAB5Tngdx8dGwpE6K9hRfngZm/cGSr6EiqZ1zZAQR9MRNd6a6d8oEPkTDZoVO7KMDrZg9L22FDmfTVSXmok5eP6YNtFlvu1X+OnP1PSENqPMUS65lzbgw/HrWKssy8Uj+vLJbwWCLWdtfD8pKbKbCCDe3kgM7IDGIjQ8/iX79c5JhipL+144dpVzklesW7iu+FHUroLFdYZKGpEYoaya9FTRK0TKDPx2eq6mWbmsZE9GODyzvEVQmiabFdLsqHzgHNnAAyaH6Eg3NC4XmclqDLcvkcW021Jb3Mbrh6PaFCZrbwHqaVJCk0tmlEQ3BWHZVVknPRask=
  app: hackduke-admin
  on:
    repo: hack-duke/hackduke-admin
